### ISSUE TITLE
Infografía-Salathiel

### ISSUE THREAD

**Issue by salathiel1999** [SistemasTecTlaxiaco/infografia-de-calidad-servitlax#2]
[Info-calidad.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-calidad-servitlax/files/8904398/Info-calidad.pdf)

**Comment by salathiel1999** [comment]
[Info-calidad.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-calidad-servitlax/files/8904393/Info-calidad.pdf)

**Comment by carlos-chrs** [comment]
calificado 20/20
