### ISSUE TITLE
Infografia-Calidad de software

### ISSUE THREAD

**Issue by Rosa218** [SistemasTecTlaxiaco/infografia-de-calidad-servitlax#3]
[Ingenieria de.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-calidad-servitlax/files/8906246/Ingenieria.de.pdf)

**Comment by carlos-chrs** [comment]
calificado 20/20

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado...
